<?php
$z[0]=Array("channel","\r\n[field:typename/]\r\n[field:typedir/]\r\n[field:typedir function='md5(@me)'/]\r\n\r\n[field:sitepath runphp='yes']\r\n	@me=(@me==\"\")?\"空的\":@me;\r\n[/field:sitepath]\r\n-----------!!!!!!!\r\n[field:global.cfg_soft_lang/]\r\n[field:sitepath function='abc(@me)'/] \r\n<br>\r\n",11,315);
$z[0][4]['type']="top";
$z[0][4]['row']="8";
$z[1]=Array("global","",344,372);
$z[1][4]['name']="cfg_soft_lang";

?>